### PR TITLE
Fix readItemsFromQueue() CPU 100%, fix various data races, fix hang when all items are deduplicated

### PR DESCRIPTION
**Pull request by yzqzss**
Also added an asset_refer_fixer.go for crawling assets that deny cross-site referers.

### CODE REVIEW

**Comment by yzqzss** [comment]
```
git checkout main && go build # build latest Zeno
rm jobs/ -rf # clean
./Zeno get url http://example.com --api --debug --local-seencheck # first run, OK
./Zeno get url http://example.com --api --debug --local-seencheck # rerun, hang and cpu 100%!
```

image

HostPool has `TotalCount` and `ActiveCount` for each host.

## TotalCount:

After each item enters PushChan, the `writeItemsToQueue()` goroutine puts the item into `prefixQueue(Frontier.Queue)` and do `TotalCount+1` for that item's host in HostPool

Then the `readItemsFromQueue()` goroutine iterate HostPool, obtains items from prefixQueue with the host in HostPool as the key, and puts those items into `PullChan`. After that, it do `TotalCount-1` for that item's host in HostPool

// The purpose is to balance the requests of each host.

So `TotalCount` represents how many items a host needs to get from `readItemsFromQueue()`, rather than how many have been crawled.

https://github.com/internetarchive/Zeno/blob/1b95ca02f18c8bf9e08b516292728cfa9833634f/internal/pkg/frontier/frontier.go#L38
(^^the code comment is wrong^^)

## ActiveCount:

`ActiveCount` indicates how many workers are currently processing requests (`executeGET()`) for this host.

The `Worker` takes an item from `PullChan` and then processes it.

An item can generate multiple requests: request for the item itself and request(s) for the item's assets.
Then, each time a request is executed (`executeGET()`), `IncrHostActive()` is called and then DecrHostActive() is deferred.
However, when `IncrHostActive()` is called, `TotalCount` is also added buggy,

https://github.com/internetarchive/Zeno/blob/1b95ca02f18c8bf9e08b516292728cfa9833634f/internal/pkg/frontier/host_pool.go#L57

causing `readItemsFromQueue()` to think that there are still unobtained items of this host in `prefixQueue`, so it frantically loops `for range(prefixQueue)`, but nothing can be retrieved, pushing CPU usage to 100%.

https://github.com/internetarchive/Zeno/blob/1b95ca02f18c8bf9e08b516292728cfa9833634f/internal/pkg/frontier/manager.go#L87

----

So, `HostPool` should not be persisted.

----

## catchFinish

When I run Zeno for the second time:

- The input URLs are deduplicated by `seencheck`, so no items are put into `pullChan`

https://github.com/internetarchive/Zeno/blob/1b95ca02f18c8bf9e08b516292728cfa9833634f/internal/pkg/frontier/manager.go#L20-L30

- Since no items are processed, `CrawledSeeds+CrawledAssets==0` always, so `catchFinish()` is stuck in waiting forever.

https://github.com/internetarchive/Zeno/blob/1b95ca02f18c8bf9e08b516292728cfa9833634f/internal/pkg/crawl/finish.go#L16-L19

**Comment by CorentinB** [comment]
Hi! I **love** your contribution, thank you so much for it. Although.. We are in the process of rewriting the entire queue. Most is already done and it should be merge around the end of the week-end I hope or next week, but you are basing your changes on main which doesn't include the new queue code.

https://github.com/internetarchive/Zeno/pull/78

Considering that your code touch the host pool for example, which is not a thing in the new queue code (we keep hosts balancing but we do it another way), could you base your PR on the `queue` branch please? You are more than welcome to do analysis / tracing / debugging of the queue branch, we know it's not perfect and it's why it's not merged yet, any help is more than welcome!

Thanks again for your contribution.

**Comment by equals215** [comment]
Very good analysis and contribution thanks a lot @yzqzss 
Will review that later today

**Comment by yzqzss** [comment]
> ...it should be merge around the end of the week-end I hope or next week, but you are basing your changes on main which doesn't include the new queue code...

> ...we're working on a new version of the queue on queue...

Thank you!

I wasn't sure how soon #78 would be merged before, and then I saw #80, so I decided to make this PR to fix the main branch.

I suppose if this PR gets merged, resolving the merge conflict in #78 will be painful, lol.
I'll close this and make a new PR based on the queue branch.

**Comment by CorentinB** [comment]
@yzqzss thanks a lot and sorry for the trouble. I tried to send you a DM on Twitter btw but I can't so if you want you can send me one and we can talk more informally there.

**Pull request closed without merging**
