### PR TITLE
Enable `log` package to distribute a stored logger to all other packages

### PR DESCRIPTION
**Pull request by equals215**

### CODE REVIEW

**Review by CorentinB — APPROVED** [review]
LGTM (but test doesn't pass)

**Comment by equals215** [comment]
> Looks good to me (but test doesn't pass)

weird I might have broken smth, on it

**Comment by equals215** [comment]
found the error : `once.Do()` is called inside of a `once.Do()` when `DefaultOrStored()` is called and no logger exists already

**Comment by equals215** [comment]
tests wont pass due to #118, merging

**Pull request merged**
